### ISSUE TITLE
Fixed Column and Row

### ISSUE THREAD

**Issue by AlbertAssaad** [ISchwarz23/SortableTableView#75] opened 2016-12-15 09:55 UTC
Hello, 
is there anyway to get the first column and first row fixed?
Thank you

**Comment by tracerTres** [comment] 2016-12-15 13:38
Hi @AlbertAssaad 
I think your issue is related to #72. You can check @ISchwarz23's reply on that issue.

**Comment by ISchwarz23** [comment] 2017-01-21 12:21
Closed because this is a duplicate of #72

**Closed by ISchwarz23** 2017-01-21 12:21 UTC
