### ISSUE TITLE
Header titles not showing.

### ISSUE THREAD

**Issue by CoolCommando** [ISchwarz23/SortableTableView#74] opened 2016-12-13 05:26 UTC
Hi, 
I have this problem with the latest version(2.4.1)- Header text does not appear when the SortableTableView is used in a fragment. The header is just a blank space. I can set the Header background color using the sortableTableView.setHeaderBackgroundColor(). No methods in the SimpleTableHeaderAdapter class seem to be working.
Note that if I use the older version- 0.9.4 the the header text does appear.

My code inside the onCreateView of the Fragment:

SimpleTableHeaderAdapter headerAdapter = new SimpleTableHeaderAdapter(mContext, "A", "B", "C", "D");
headerAdapter.setTextColor(Color.parseColor("#000000"));

    TableView<String[]> sortableTableView = (TableView<String[]>)        rootView.findViewById(R.id.tableView);
    sortableTableView.setDataAdapter(new SimpleTableDataAdapter(mContext, DATA_TO_SHOW));
    sortableTableView.setColumnCount(4);
    sortableTableView.setHeaderBackgroundColor(Color.parseColor("#FFFFFF"));
    sortableTableView.setHeaderElevation(10);
    sortableTableView.setHeaderAdapter(headerAdapter);

Layout:

<de.codecrafters.tableview.SortableTableView
android:id="@+id/tableView"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:layout_margin="5dp"
android:background="#dafdea"
/>

Please let me know if I'm doing anything incorrectly.

Thanks.

**Comment by CoolCommando** [comment] 2016-12-13 06:06
I just tried using this inside an activity and have the same issue. Using the old version(0.9.4) works. 
Details of my project: compileSdkVersion 25
    buildToolsVersion "25.0.1"
     minSdkVersion 23
        targetSdkVersion 25

The device I'm testing on also is API 25. Could this be a compatibility issue with Nougat?

**Comment by jawherjouini** [comment] 2016-12-14 16:33
I had this same issue on 4.1.2 and 4.4.3 devices with 2.4.1 version so I had to downgrade to 2.3.0. I don't think it is a compatibility issue.

**Comment by tracerTres** [comment] 2016-12-14 18:22
Hi @CoolCommando 
I think your issue is a duplicate of #70. There are some workarounds suggested there that could help before the issue is fixed

**Comment by ISchwarz23** [comment] 2017-01-21 12:20
Closed because of duplicate of #70

**Closed** 2017-01-21 12:24 UTC
